### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by cbertinato** [DynamicGravitySystems/DGP#32]
I propose that the goal for this release is basic QC functionality, mainly so we can do some testing in the field.  Let's use this issue to track features that we think would be necessary for this use case in the form of a checklist.  We can modify and fill this in until we're happy with it.

- [x] Import DGS, ZLS, and trajectory data
- [x] User can plot any gravity and trajectory channel available (Issue #36)
- [ ] Toggle status bits on plots: Show DGS status on plots; ZLS does not record status
- [x] ~~Join gravity data with trajectory data~~ Won't Do.
- [x] Eotvos correction (Issue #28)
- [x] Align gravity and GPS
- [x] Segmentation into lines: just finish labeling (Issue #35; PR #45)
- [x] Some filtering: simple low pass with user-definable cut-off (filter length) (Issue #25)
- [ ] Compute standard deviation of raw gravity
- [ ] Compute free air anomaly
- [ ] Export processed data (Issue #38)
- [ ] Some sort of indicator for gaps in trajectory and gravity data

**Comment by bradyzp** [comment]
Sounds like a good plan, lets talk about dividing up different areas here and begin work towards this as soon as we finish with the current gui-dev branch.

**Comment by cbertinato** [comment]
Modified a few of the checklist items. Is Eotvos good to go? I can pick up gravity and trajectory dataframe join after I finish the labeling code. I have some code for alignment, but need to do some work on sub-sample rate alignment. I also have some filtering code that just needs some tests.

**Comment by bradyzp** [comment]
Eotvos is good to go, just ensure it is utilizing the basic derivative function for now.
The numpy.gradient needs some adjustment and testing before it can be used.
