### ISSUE TITLE
ENH: Interface Improvements

### ISSUE THREAD

**Issue by bradyzp** [DynamicGravitySystems/DGP#41]
List of interface improvements that need to be accomplished at some point, for tracking purposes:
- [x] Icons for Data Files based on type (GPS/Gravity)
- [x] Ability to delete Flights, Data files etc. from the Tree View
- [x] Display Data Files in Tree View in a informative way e.g. <Type>: Filepath
- [ ] Add ability to show more detailed information for items via context menu (similar to Flight info menu)
- [ ] ~~Context menu for Data Channels to remove all/remove all from specific plot~~
- [x] Fix TreeView style sheet to display arrows on all expandable menus
- [ ] Improve loading splash-screen functionality: enable button to clear recent. Option to sort by date.

**Comment by bradyzp** [comment]
Adding to this list of things to do in the GUI department - post merge of PR #69 

- [x] Implement cross-platform application state management using QSettings (track recent projects, window size, open flights etc)) [in progress]
- [ ] Use Qt stylesheets to control various interface styling (see issue #70 ) - possibly add ability for user to select font type/size etc through dialog menu (and remember the setting using QSettings).
- [ ] Improve the QMenu system used for the project tree, possibly enabling inheritance of menu items from a parent.
- [x] Flatten the project tree, remove the Datasets folder; DataSet will become a direct child of its Flight. Sensors folder may also be removed, sensor links can be added to a DataSet. (resolved by #79 )
- [x] Enable loading/opening of multiple projects within the main window/project tree - this may require some project updates but I think is almost doable. (resolved by #76 )
- [x] DataSet Segments need the ability to be deleted by the user via GUI action.
- [ ] Add a dialog/menu action that allows a user to create or edit a DataSegment (as opposed to click-dragging on the plot surface)
- [ ] Add a dialog that allows the user to inspect an imported Data File (i.e. Gravity/Trajectory data), displaying statistics ala DataFrame.describe(), and allowing the user to browse the raw data using a QTableView (possibly enabling editing).
