### ISSUE TITLE
Tracking: feature/ui-improvements

### ISSUE THREAD

**Issue by bradyzp** [DynamicGravitySystems/DGP#82]
Branch Tracking Issue for feature/ui-improvements
=================================
**Overview:**
This branch will focus on various usability improvements to the DGP user interface. Improving user interaction with the plotters, updating icons/visual elements, integrating work on user settings (persistent application state), etc.

**Goals:**
- [x] Implement more user friendly plot controls for plotting data channels on different plots/axis' in line selection plot
- [x] Integrate User Settings features, e.g. saving/restoring window position, improving recent-projects tracking/loading, restoring tabs to their last state (plotted lines etc)
- [x] Add ability to hide/show segment selections on the LineSelectPlot
- [x] Refactor workspace tab interface, create specific tab classes for different controllers (i.e. Project/Flight/DataSet).
- [x] Add basic workspace tab state persistence, i.e. the plot tab will restore whichever series were plotted when it was last closed.

**Future Branch:**
- [ ] Implement custom UI Dialog for displaying formatted text e.g. for in-application help, graph-transform source etc. Similar to a QMessageDialog but with customizable central widget e.g. a QTextEdit or QTextBrowser
- [ ] Add option menu to plots enabling user to select the number of rows/columns (within limits) of plots to display. (may need to trigger a complete reload of the tab).
